### ISSUE TITLE
Add separator between two sequential endnote references

### ISSUE THREAD

**Issue by nivaca** [cgnieder/enotez#22]
Say I have the following:
`text\endnote{foo}\endnote{bar}`

This gets set as:
![image](https://user-images.githubusercontent.com/2309005/90207620-5b0e5200-ddac-11ea-8c84-ef51e2e94010.png)

Some classes and packages automatically insert a separator between the note references, e.g.:
![image](https://user-images.githubusercontent.com/2309005/90207659-77aa8a00-ddac-11ea-8e4c-3b36ad928011.png)

I'm working on a large project contaning XSLT-generated LaTeX code, so it's difficult to manually insert the separators.

Can you please include this functionality in enotez? Thanks.

**Comment by cgnieder** [comment]
Would adding [fnpct](https://github.com/cgnieder/fnpct) be a solution for you?

```latex
\documentclass{article}
\usepackage{enotez,fnpct}
\begin{document}
text\endnote{foo}\endnote{bar}
\end{document}
```

**Comment by nivaca** [comment]
Interesting package. Thanks. But it doesn't solve my issue.

**Comment by cgnieder** [comment]
Why not? What is your issue?

**Comment by nivaca** [comment]
Sorry. It did. At first it simply kerned the two endnote anchors. Thanks!
