### ISSUE TITLE
Insert Chapter Title after chapter number

### ISSUE THREAD

**Issue by Kalaschnik** [cgnieder/enotez#24]
Hey,
I’m so glad there is an endnotes package that supports hyperref by default. I’m trying to understand your documentation. However, I find no possibility to add the chapter text to my printout.

I got this code the split endnotes into chapters: 
```tex
\usepackage{enotez}
\setenotez{
    list-name={Anmerkungen zu den Kapiteln},
    split=chapter,
    list-style=chapter
}
\DeclareInstance{enotez-list}{chapter}{paragraph}{heading=\chapter*{#1}}
```

Which results into:
![image](https://user-images.githubusercontent.com/9831678/104228096-a6f02080-544a-11eb-8b6c-ae168f9d7fdc.png)

What I would like: (1) Remove the notes label for the individual chapter (as this is redundant), and append the chapter title after the chapter number. For example, instead of:  `Anmerkungen zu Kapitel 1` I want to get `Kapitel 1: Intoduction`

**Comment by cgnieder** [comment]
Have a look at this: https://tex.stackexchange.com/questions/512089/

Please note that this will only work for _numbered_ chapters.

**Comment by Kalaschnik** [comment]
That did the trick. But I’m not sure if this was causing some hyperref offset issues:
![GIF 12 01 2021 09-52-57](https://user-images.githubusercontent.com/9831678/104291615-076b7600-54bc-11eb-80d9-ee92a7719b55.gif)

**Comment by Kalaschnik** [comment]
Anyway, consider this issue as solved. I opened #25 with my follow-up issue.
