### ISSUE TITLE
Hide/Disable list-name

### ISSUE THREAD

**Issue by Kalaschnik** [cgnieder/enotez#25]
Due to #24, I’m trying to bypass wrong hyperref targets by disabling the headline (i.e., `list-name` which defaults to _Notes_), and make a normal `\chapter`

Is there a way to disable inserting a list-name?

**Comment by cgnieder** [comment]
Yes, of course.

![image](https://user-images.githubusercontent.com/2248538/104346875-34da1300-5500-11eb-8a34-6d157e871543.png)

This means you can either use
```latex
\setenotez{ list- heading = }
```
in order to disable the heading completely. The you can do
```latex
\chapter{Whatever it should be}
\printendnotes
```
Or you set
```latex
\setenotez{ list- heading = \chapter{Whatever it should be} }
```
or
```latex
\setenotez{
  list- heading = \chapter{#1} ,
  list-name = Whatever it should be
 }
```
and still only use
```latex
\printendnotes
```

**Comment by Kalaschnik** [comment]
Thanks, I just figured out the "bug". As soon as I’m using the * version for chapter the hyperref target will fail. Not sure if this some other latex/package problem... Do you have a clue?

**Comment by cgnieder** [comment]
I have no idea what you are talking about… I need to to see a MWE (minimal working example, with emphasis on _minimal_, but complete, ie., starting with `\documentclass` end ending with `\end{document}`) which lets me reproduce your issue on my system. But please do so with a new issue or on https://tex.stackexchange.com

_This_ issue is solved I believe…
