### ISSUE TITLE
enotez: kernel/command-not-defined

### ISSUE THREAD

**Issue by loting** [cgnieder/enotez#26]
When I use the wiley template(wiley-article.cls) in WinEdit, there are many errors.
Latex error: kernel/command-not-defined. Control sequence \str_if_in:nnT undefined.
Undefined sequence RequirePackage {expl3 xparse.l3keys2e,xtemplate} no page of output.

![image](https://user-images.githubusercontent.com/24785017/112617707-43c63580-8e60-11eb-85fd-c9513aedc707.png)
![image](https://user-images.githubusercontent.com/24785017/112617748-550f4200-8e60-11eb-9b31-64b574a7632e.png)

**Comment by cgnieder** [comment]
Hi. Your version of `enotez` is newer than your version of LaTeX.

You should (almost) never update single packages but always the distribution.

**Comment by loting** [comment]
> Hi. Your version of `enotez` is newer than your version of LaTeX.
> 
> You should (almost) never update single packages but always the distribution.
