### ISSUE TITLE
`totoc` option with classes that have `\chapter` results in wrong page in ToC

### ISSUE THREAD

**Issue by gusbrs** [cgnieder/enotez#32]
For document classes which have `\chapter`, `enotez` uses by default `\chapter*` to set the `\printendnotes` heading. The `totoc` option will set a `\phantomsection` in order to add the entry to the ToC. However, since that is done before `\chapter*`, and `\chapter*` issues a `\cleardoublepage` internally, the page for the Notes (and, as a consequence, also its hyperlink) will be wrong.

A MCE for the issue:

```latex
\documentclass{book}

\usepackage{enotez}
\setenotez{totoc}
\usepackage{lipsum}
\usepackage{hyperref}

\begin{document}

\tableofcontents{}

\chapter{Chapter 1}

\lipsum[1-2]\endnote{\lipsum[3]}

\chapter{Chapter 2}

\lipsum[1-2]\endnote{\lipsum[3]}

\printendnotes

\end{document}
```
Results in ToC:

![Screenshot from 2022-03-18 08-43-55](https://user-images.githubusercontent.com/19410606/158997343-ff111ddd-55fe-44c0-892f-6303ef53f147.png)

But:

![Screenshot from 2022-03-18 08-44-15](https://user-images.githubusercontent.com/19410606/158997351-ddd12bf7-395e-4d56-9a6b-c378f1ec9542.png)

**Comment by cgnieder** [comment]
Thanks, fixed.

**Comment by gusbrs** [comment]
Thank you very much! And wow!, you're fast today. ;-)  (I still have some more stuff coming, I'm really diggin' this very cool package of yours).

I do have a comment on the solution you adopted here. That was the first thing I thought of doing as well, but I was not really sure it was the best solution. Because in setting a `\phantomsection` after the heading (be it `\section*` or `\chapter*`) the anchor will be placed *below* the heading. As a result, depending a little on your viewer, clicking on the hyperlink in the ToC will scroll the page just enough to actually hide the heading.

The other idea I had would be, instead of swaping the order, to issue `\cleardoublepage` or `\clearpage` (as appropriate, depending on whether chapter exists, and on the value of `openright`) before calling `\enotez_set_totoc:`.

Admittedly, this would be somewhat more complex, and be more fragile to different scenarios (if the documentclass does something different there, for example). I'm also not sure if we wouldn't get an undue extra empty page or spread in so doing (I think not though). So, I'm not sure it is better, just bringing in some thoughts for your consideration.

**Comment by cgnieder** [comment]
Actually, in the long term I like to drop the option `totoc` and just let the user set whichever sectioning command and list preamble they want…

The current obviously is… improvable.

**Comment by gusbrs** [comment]
It makes sense. I've just been using `list-heading=\addchap{#1},` myself.  ;-)
