### ISSUE TITLE
`split` + `reset` + `hyperref` results in duplicate anchors (and thus wrong reference links)

### ISSUE THREAD

**Issue by gusbrs** [cgnieder/enotez#33]
Currently, the combined use of of option `split` and `reset` alongside `hyperref` results in duplicate anchors/destinations for the resulting endnotes. As a consequence, references made to endnotes may get incorrect links.

A MCE that illustrates the issue:

```latex
\documentclass{book}

\usepackage{enotez}
\setenotez{
  split=chapter,
  reset,
}
\usepackage{lipsum}
\usepackage{hyperref}

% This gets us unique anchors and working links.
% \def\theHendnote{\thechapter.\arabic{endnote}}

\begin{document}

\tableofcontents{}

\chapter{Chapter 1}

\lipsum[1-2]\endnote{\lipsum[3]}\label{en:1}

\lipsum[1-2]\endnote{\lipsum[3]}\label{en:2}

\chapter{Chapter 2}

\lipsum[1-2]\endnote{\lipsum[3]}\label{en:3}

\lipsum[1-2]\endnote{\lipsum[3]}\label{en:4}

\printendnotes

\cleardoublepage{}

\ref{en:1}

\ref{en:2}

\ref{en:3} % this will link to 'en:1'

\ref{en:4} % this will link to 'en:2'

\end{document}
```
We will find in the `.aux` of this file:
```
\newlabel{en:1}{{1}{3}{Chapter 1}{endnote.1}{}}
\newlabel{en:2}{{2}{4}{Chapter 1}{endnote.2}{}}
\newlabel{en:3}{{1}{5}{Chapter 2}{endnote.1}{}}
\newlabel{en:4}{{2}{6}{Chapter 2}{endnote.2}{}}
```
And in the `.log`, the corresponding warnings:
```
Chapter 2.
pdfTeX warning (ext4): destination with the same identifier (name{endnote.1}) h
as been already used, duplicate ignored
<to be read again> 
                   \relax 
l.23 \lipsum[1-2]\endnote{\lipsum[3]}
                                     \label{en:3}pdfTeX warning (ext4): destina
tion with the same identifier (name{endnote.2}) has been already used, duplicat
e ignored
<to be read again> 
                   \relax 
```
And, that given, the hyperlinks generated by `\ref{en:3}` and `\ref{en:4}` will bet incorrectly placed to `en:1` and `en:2` respectively.

A possible solution to generate unique anchors, is to set the format of `\theHendnote` with something like:

```latex
\def\theHendnote{\thechapter.\arabic{endnote}}
```
Disclaimer: `hyperref` is somewhat a land of mystery to me, so I'm not sure if this is the "proper" solution. But it does get us unique anchors and correctly working links.

**Comment by cgnieder** [comment]
Thanks. I'll set `\theHendnote` to `\theHchapter.\theendnote` (or `\theHsection.\theendnote` depending...)

**Comment by gusbrs** [comment]
Thank you very much!

**Comment by gusbrs** [comment]
@cgnieder It turns out my suggested fix for this, even if reasonable, might not have been the ideal one (for why, see the discussion at https://github.com/latex3/hyperref/issues/230).

I think a better alternative would be to use the following where appropriate (instead of the previously suggested procedure):

```latex
\bool_if:NT \l__enotez_split_bool
  {
    \tl_if_eq:VnTF \l__enotez_split_tl {section}
      {
        \hook_gput_code:nnn {cmd/section/before} {enotez}
          { \int_gincr:N \g__enotez_list_printed_int }
        \bool_if:NT \l__enotez_reset_bool
          { \counterwithin* {endnote} {section} }
      }
      {
        \hook_gput_code:nnn {cmd/chapter/before} {enotez}
          { \int_gincr:N \g__enotez_list_printed_int }
        \bool_if:NT \l__enotez_reset_bool
          { \counterwithin* {endnote} {chapter} }
      }
  }
```
Since this is run at `begindocument`, we'd be sure to get `hyperref`'s version of `\@addtoreset`, and this would keep `hyperref` happy with unique destinations by its own means. If `hyperref` is not present, the kernel's `\counterwithin*` just resets the counter as you'd expect (I don't know about the `enotez` backward compatibility policy, but `\counterwithin` has been on the kernel for some years now, previously it was provided by `chngcntr`).

**Comment by cgnieder** [comment]
I can't even remember why I didn't use `\@addtoreset` (or `\counterwithin*` – its available in the kernel since 2018) in the first place…
