### ISSUE TITLE
Set `\@currentcounter` in `\enotez_endnote_mark:n`

### ISSUE THREAD

**Issue by gusbrs** [cgnieder/enotez#35]
`\enotez_endnote_mark:n` runs `\refstepcounter {endnote}` in case `\endnote` or `\endnotemark` received no optional argument. And, in case they did, `\@currentlabel` is set manually.  However, since some time now, `\refstepcounter` sets not only `\@currentlabel`, but also `\@currentcounter`. I'd like to suggest that `\enotez_endnote_mark:n` also set `\@currentcounter` in case the optional argument is given. This practice is encouraged by the "Team" (see https://www.latex-project.org/news/latex2e-news/ltnews34.pdf, section "Extended label handling in package code").

It'd be enough to add right after setting `\@currentlabel`:

```latex
\cs_gset:cpn {@currentcounter} {endnote}
```
(For some context, see https://github.com/latex3/latex2e/issues/300 and https://github.com/latex3/latex2e/issues/687)

**Comment by cgnieder** [comment]
Thanks, done.

**Comment by gusbrs** [comment]
And, again, thank you very much!
