### ISSUE TITLE
`\enotez_print_endnotes:nn` first argument

### ISSUE THREAD

**Issue by gusbrs** [cgnieder/enotez#39]
Perhaps I'm missing something, but I cannot understand what is being done with the first argument of `\enotez_print_endnotes:nn`:

https://github.com/cgnieder/enotez/blob/a8e8d2d8ce47328a7d7958069851517143ce77d8/enotez.sty#L703-L716

As far as my reading goes the `{#1}` at line 710 is loose there, no-op, and possibly leaking into the stream.

**Comment by cgnieder** [comment]
It's an argument to `\UseInstance` which passes it on to `\enotez_build_print_list:nnnn`.

**Comment by gusbrs** [comment]
Ah! So I was missing something indeed. It is just my lack of acquaintance with `xtemplate`. Sorry for the noise.
