### ISSUE TITLE
Extra vertical space in raised link at `\enotez_write_list_number:n`

### ISSUE THREAD

**Issue by gusbrs** [cgnieder/enotez#42]
When `\enotez_write_list_number:n` sets the hyperlink target for the footnote, it raises the link, as it should, but does so by a hard-coded amount of `1em`. This is done by:

```latex
\box_move_up:nn {1em} { \hbox:n { \hypertarget {enz.#1} { } } }
```
While with the default settings this poses no problems, if users attempt to achieve a more "compact" set of endnotes, they will remain with a residual vertical space between items/paragraphs, resulting from the above. For example, an attempt to ensure that the endnotes section fits an exact number of lines in the typeblock (a frequent typographical recommendation, so that the lines are aligned in both sides of the spread and the leaf), would become impossible because the size of the page will depend on the number of endnotes in the page, which is unknowable beforehand.

The document below illustrates the use of a custom `enumitem` list environment for the endnotes, where I set `noitemsep`, so as to (supposedly) eliminate the vertical space between items.

```latex
\documentclass[11pt]{scrbook}

\KOMAoptions{
  paper=234mm:156mm, % small royal octavo
  DIV=12, % DIV calls '\typearea' and recalculates it.
  headings=normal, % less large headings.
}

\usepackage{enumitem}

\usepackage{enotez}
\setenotez{
  list-heading=\addchap{#1},
  list-style=customendnotes,
  split=chapter,
  backref,
  reset,
}

\newlist{customendnotes}{description}{4}
\setlist[customendnotes]{
  leftmargin=1em,
  listparindent=1em,
  labelsep=.2em,
  noitemsep,
}

\DeclareInstance{enotez-list}{customendnotes}{list}{
  list-type = customendnotes,
  format = \small,
}

\usepackage{lipsum}
\usepackage{showframe}
\usepackage[hidelinks]{hyperref}

\ExplSyntaxOn
\NewDocumentCommand \testchapter {}
  {
    \prg_replicate:nn { 25 }
      {
        \lipsum[1]\endnote{\lipsum[][1-5]}
        \lipsum[1]\endnote{\lipsum[][6-14]}
        \lipsum[1]\endnote{\lipsum[][15-16]}
        \lipsum[1]\endnote{\lipsum[][17-25]}
        \lipsum[1]\endnote{\lipsum[][26-28]}
        \lipsum[1]\endnote{\lipsum[][29-40]}
      }
  }
\ExplSyntaxOff

\begin{document}

\tableofcontents

\chapter{Chapter 1}

\testchapter

\chapter{Chapter 2}

\testchapter

\printendnotes

\end{document}
```

![Screenshot from 2022-03-22 13-00-34](https://user-images.githubusercontent.com/19410606/159525977-6820bbd8-ff9d-4965-8bd2-d8fdcf2d57cb.png)

Note the lines are not aligned. Also, this page has a `\textheight` of `500.6pt` which should fit 41 lines of `\small` text (in this document with fontsize 10pt, and leading 12pt, for `\small` that is). However, the pages range between 39 to 40 lines, depending on the number of endnotes. The reason is the one raised hyperlink, mentioned above.

I'd suggest using the following instead (or some equivalent form):

```latex
\Hy@raisedlink { \hypertarget {enz.#1} { } }
```
A document set with that adjustment, and a small leading correction for the end notes provides better results (and expected 41 lines per page):

```latex
\documentclass[11pt]{scrbook}

\KOMAoptions{
  paper=234mm:156mm, % small royal octavo
  DIV=12, % DIV calls '\typearea' and recalculates it.
  headings=normal, % less large headings.
}

\usepackage{enumitem}

\usepackage{enotez}
\setenotez{
  list-heading=\addchap{#1},
  list-style=customendnotes,
  split=chapter,
  backref,
  reset,
}

\newlist{customendnotes}{description}{4}
\setlist[customendnotes]{
  leftmargin=1em,
  listparindent=1em,
  labelsep=.2em,
  parsep=\parskip, % 0pt plus 1pt
  itemsep=0pt,
  % noitemsep,
}

\DeclareInstance{enotez-list}{customendnotes}{list}{
  list-type = customendnotes,
  format = \small,
}

\AddToHook{env/customendnotes/begin}{\linespread{1.0199966}\selectfont}

\usepackage{lipsum}
\usepackage{showframe}
\usepackage[hidelinks]{hyperref}

\makeatletter
\ExplSyntaxOn
\cs_set_protected:Npn \enotez_write_list_number:n #1
  {
    \bool_if:NT \l__enotez_hyperfootnotes_bool
      {
        % \box_move_up:nn {1em} { \hbox:n { \hypertarget {enz.#1} { } } }
        \Hy@raisedlink { \hypertarget {enz.#1} { } }
      }
    \tl_use:N \l__enotez_list_number_format_tl
    \bool_lazy_and:nnTF
      { \l__enotez_hyperfootnotes_bool }
      { \l__enotez_hyperbackref_bool }
      {
        \exp_args:Nnx
        \hyperlink {enz.#1.backref}
          { \exp_not:V \l__enotez_endnote_mark_tl }
      }
      {
        \str_if_eq:neTF {a} { \prop_item:Nn \g__enotez_endnote_man_prop {#1} }
          { \prop_item:Nn \g__enotez_endnote_mark_prop {#1} }
          { \exp_not:V \l__enotez_endnote_mark_tl }
      }
  }

\NewDocumentCommand \testchapter {}
  {
    \prg_replicate:nn { 25 }
      {
        \lipsum[1]\endnote{\lipsum[][1-5]}
        \lipsum[1]\endnote{\lipsum[][6-14]}
        \lipsum[1]\endnote{\lipsum[][15-16]}
        \lipsum[1]\endnote{\lipsum[][17-25]}
        \lipsum[1]\endnote{\lipsum[][26-28]}
        \lipsum[1]\endnote{\lipsum[][29-40]}
      }
  }
\ExplSyntaxOff
\makeatother

\begin{document}

\tableofcontents

\chapter{Chapter 1}

\testchapter

\chapter{Chapter 2}

\testchapter

\printendnotes

\end{document}
```
![Screenshot from 2022-03-22 13-09-02](https://user-images.githubusercontent.com/19410606/159526033-55b8a29b-5d21-468f-9d2b-cf69aa9075a8.png)

**Comment by cgnieder** [comment]
Thanks for this and for the fix. Added for the next release.

**Comment by gusbrs** [comment]
Thank you!

**Comment by gusbrs** [comment]
I'm not sure this is exactly the same, but this is a related question https://tex.stackexchange.com/a/494946. And it seems `\enotez_write_mark:nn` would also welcome the same fix as `\enotez_write_list_number:n`
