### ISSUE TITLE
When I use enotez.sty package console shows "LaTeX error:'kernel/command-not-defined'".

### ISSUE THREAD

**Issue by Cz1544252489** [cgnieder/enotez#46]
here is the error log:

! LaTeX error: "kernel/command-not-defined"
! 
! Control sequence \str_if_in:nnT undefined.
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.68 \cs_generate_variant:Nn \str_if_in:nnT
                                            { o }
? 
Process has been killed ...

I have tried to find why the issue arises, and when I comment the line 68 in file enotez.sty other error log shows:

! Undefined control sequence.
l.141 \str_new:N
                 \l__enotez_tmpa_str
? H
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
? 
Process has been killed ...

So I guess what I can`t address is from the file enotez.sty and I hope to get some help. Thanks a lot!

**Comment by Bes7e** [comment]
Can you fix these issues?

Thanks a lot!

**Comment by Cz1544252489** [comment]
I solve the problem by updating the Miktex app, so I can`t sure the issue is made by the enotez.sty file.
